---
- name: Update apt cache.
  apt: update_cache=yes cache_valid_time=86400
  changed_when: false

- name: Ensure nginx is installed.
  apt:
    name: 'nginx'
    state: present

- name: Set nginx main conf
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    force: true
    owner: root
    group: root
    mode: 0644
  notify: reload nginx

- name: Check for templates, sites dirs
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /etc/nginx/templates
    - /etc/nginx/sites-available
    - /etc/nginx/sites-enabled

- name: Add templates
  template:
    src: '{{ item }}.conf.j2'
    dest: '/etc/nginx/templates/{{ item }}.conf'
    force: true
    owner: root
    group: root
    mode: 0644
  with_items: "{{ nginx_templates }}"
  notify: reload nginx

- name: Add managed vhost config files
  template:
    src: 'site.conf.j2'
    dest: /etc/nginx/sites-available/{{ item }}.conf
    force: true
    owner: root
    group: root
    mode: 0644
  vars:
    v_domain: "{{ item }}"
  with_items: "{{ nginx_vhosts }}"
  notify: reload nginx

- name: Change MaxRequestWorker in mods-enabled
  replace:
    path: '/etc/nginx/sites-available/{{ item  }}.conf'
    regexp: '(^\s*root) (.*)$'
    replace: '\1 \2/wordpress'
    backup: no                                      # yes?
  with_items: "{{ domains }}"

- name: Symlink virtualhost to sites-enabled.
  file:
    src: "/etc/nginx/sites-available/{{ item }}.conf"
    dest: "/etc/nginx/sites-enabled/{{ item }}.conf"
    state: link
  with_items: "{{ nginx_vhosts }}"
  notify: reload nginx

- name: Disable default virtualhost.
  file:
    path: "/etc/nginx/sites-enabled/default"
    state: absent
  notify: reload nginx

#- name: Ensure nginx is restarted.
#  service: "name=nginx state=restarted "
