---
- hosts: deb2
  become: yes
  remote_user: root

  roles:
    - role: apache
      http_port: 80
      http_host: "*"
      servername: localhost
      domains:
        - site.ru
        - site-2.ru

    - role: php
      mysql_host: 'localhost'
      mysql_user: 'test'
      mysql_user_password: '123'
      domains:
        - site.ru
        - site-2.ru

    - role: mysql
      mysql_version: "8.0"
      mysql_root_password: 123

      mysql_databases:
        - name: exam_db
          encoding: latin1
          collation: latin1_general_ci
      mysql_users:
        - name: test_user
          host: "%"
          password: 123
          priv: "exam_db.*:ALL"


